### ISSUE TITLE
Can't get otp

### ISSUE THREAD

**Issue by ippocratis** [Benojir/Caller-ID#3]
Thows Error try 1 hour later

**Comment by Benojir** [comment]
This happens when you tried too many times. Wait 24 hours and then try again

**Comment by ippocratis** [comment]
> This happens when you tried too many times. Wait 24 hours and then try again 

Unfortunately this is not the case.
The error is appearing since the very first try.

For the record it is a Greek mobile number. The problem arise whenever a country code other than India is used . 

Awkard thing is if I use India code with my Greek number it says otp send . Obviously it never arives .......

**Comment by Benojir** [comment]
> > This happens when you tried too many times. Wait 24 hours and then try again
> 
> Unfortunately this is not the case. The error is appearing since the very first try.
> 
> For the record it is a Greek mobile number. The problem arise whenever a country code other than India is used .
> 
> Awkard thing is if I use India code with my Greek number it says otp send . Obviously it never arives .......

This is happening because this app uses Truecaller's asian server for sending OTP. You need an Asian number

**Comment by ippocratis** [comment]
> This is happening because this app uses Truecaller's asian server for sending OTP. You need an Asian number

Well if the app is made for Asian users only maybe a disclaimer in the readme stating that is needed.
